### ISSUE TITLE
Compile List of Sub groups

### ISSUE THREAD

**Issue by SCKelemen** [wearehx/policies#11]
We should probably generate a list of subgroups

**Comment by gsingh93** [comment]
Yup. After admins are elected, one thing they need to figure out is how we want to do subgroups (I have some ideas on this that I'll share with them). Once that gets figured out we can do this.

**Comment by SCKelemen** [comment]
@gsingh93 Other than admins, are the technical people who will run websites, and do technical things? I havent been following this much, lately. Been super busy with end of the year release cycles.

**Comment by gsingh93** [comment]
Yes, people other than admins can help with all of that stuff.
