### ISSUE TITLE
Archive over Destruction

### ISSUE THREAD

**Issue by SCKelemen** [wearehx/policies#5]
There is mention of the possibility of deleting or locking toxic posts. As I think its important to moderate things, I also am against the out right destruction of any post. I suggest that the post be more archived, rather than deleted. Perhaps preserving history with screen shots, or maybe I can create a bot to save the page upon removal.

**Comment by iangcarroll** [comment]
Locking == archiving?

**Comment by gsingh93** [comment]
@Err418, how closely did you read the draft content policy? It clearly states that deletion will be avoided almost entirely, except for certain exceptional cases stated in the document. Do you disagree with those exceptional cases?

**Comment by SCKelemen** [comment]
@gsingh93 I wrote that...

**Comment by gsingh93** [comment]
@Err418, I'm confused. Do you disagree with the content policy as it is now? If so, which part? If not, what is this issue about?

**Comment by gsingh93** [comment]
Further discussion should happen on either #2 or #10.
