### ISSUE TITLE
Jokes and Memes need to be restricted to their own subgroup.

### ISSUE THREAD

**Issue by zuron7** [wearehx/policies#8]
I think that the spilling of HH CdT into HH was responsible to an extent for the reduction of content quality. When new members see low quality posts they don't take the group seriously leading to the death of the group, like HH. Refer HN (hackernews), where the mildest of shit-posts are down-voted to hell. So, I recommend that the content policy should restrict all memes and jokes to their own sub group. Certain special cases can be permitted where the user uses something like a comic from XKCD and the memeing adds value of the discussion. 

I used to frequent a forum by the name http://gbatemp.net and the quality of content on their site is great despite being pretty large, which I attribute to their having a sub-forum just for joking around.

**Comment by gsingh93** [comment]
Could you please make comments relating to the content policy on the actual policy itself?

https://github.com/wearehx/policies/pull/2

**Comment by zuron7** [comment]
Sorry! Didn't see that. Will do so. Do you want me to copy paste this there? Or is the reference you've provided enough?

**Comment by RitwikGupta** [comment]
The reference is enough :)
